//
//  main.m
//  Maths
//
//  Created by Angie Linton on 2017-01-10.
//  Copyright © 2017 Angie Linton. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Addition.h"
#import "InputHandler.h"
#import "ScoreKeeper.h"
#import "QuestionManager.h"


int main(int argc, const char * argv[]) {
    @autoreleasepool {
        
        char inputChars[200];
        
        BOOL gameOn = YES;

        // create scorekeeper instance
      
        ScoreKeeper *scoreKeeper = [[ScoreKeeper alloc]init];
        QuestionManager *questionManager = [[QuestionManager alloc]init];
        
        while (gameOn) {
            
            Addition *addQ = [[Addition alloc] init];//only use the * when declaring
            
            
            // add the addition object to the the score keep instance property
            
            [scoreKeeper.mathObjects addObject:addQ];
            [questionManager.questions addObject:addQ];
            
            NSLog(@"%@", addQ.question);
            
            NSLog(@"Input answer: ");
            
            fgets(inputChars, 200, stdin);
            
            NSString *input = [NSString stringWithCString:inputChars encoding:NSUTF8StringEncoding];
            
            input = [input stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceAndNewlineCharacterSet]];
            
            if ([input isEqualToString:@"quit"]) {
                gameOn = NO;
            }

            [addQ answeredWithInput:input];
            BOOL isCorrect = addQ.correct;
            
                     
            NSLog(@"%@", isCorrect == YES ? @"You're right!" : @"You're wrong!");
            
            NSLog(@"%@", [scoreKeeper score]); //calling score from ScoreKeeper.m
        }
        
    }
    return 0;
}
//Next we have to think about where to set the endTime property. We could set it from main.m at the moment the user answers the question. This is a reasonable option. It would allow us to pass in a dummy date value to test the method if we wanted to. This is called "Dependency Injection".
//
//Instead of passing in the endTime let's override the answer getter. When main.m calls AdditionQuestion for the answer, we can set the endTime then. Remember Objective-C properties are just getter and setter methods. These are automatically generated by the compiler. So, let's go ahead and override the answer getter and set the endTime property like this:
